-- MySQL Script generated by MySQL Workbench
-- Sun Nov 24 18:46:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_registra_pessoas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_registra_pessoas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_registra_pessoas` DEFAULT CHARACTER SET utf8 ;
USE `bd_registra_pessoas` ;

-- -----------------------------------------------------
-- Table `bd_registra_pessoas`.`brp_enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_registra_pessoas`.`brp_enderecos` (
  `end_codigo` INT NOT NULL AUTO_INCREMENT,
  `end_cep` INT NOT NULL,
  `end_logradouro` VARCHAR(45) NOT NULL,
  `end_numero` INT NOT NULL,
  `end_bairro` VARCHAR(45) NOT NULL,
  `end_cidade` VARCHAR(45) NOT NULL,
  `end_estado` VARCHAR(45) NOT NULL,
  `end_pais` VARCHAR(45) NOT NULL,
  `end_pes_codigo` INT NOT NULL,
  INDEX `fk_end_pes_codigo_idx` (`end_pes_codigo` ASC),
  PRIMARY KEY (`end_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_registra_pessoas`.`brp_pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_registra_pessoas`.`brp_pessoas` (
  `pes_codigo` INT NOT NULL AUTO_INCREMENT,
  `pes_cpf` DOUBLE NOT NULL,
  `pes_nome` VARCHAR(50) NOT NULL,
  `pes_senha` VARCHAR(32) NOT NULL,
  `pes_data_nascimento` DATE NOT NULL,
  `brp_pes_end_codigo` INT NULL,
  `pes_email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`pes_codigo`),
  INDEX `fk_brp_pes_end_codigo_idx` (`brp_pes_end_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_brp_pes_end_codigo`
    FOREIGN KEY (`brp_pes_end_codigo`)
    REFERENCES `bd_registra_pessoas`.`brp_enderecos` (`end_pes_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;