DROP procedure IF EXISTS `P_OBTEM_PESSOAS`;
CREATE PROCEDURE `P_OBTEM_PESSOAS`(P_CODIGO INT,
								   P_DATA_INI   VARCHAR(11),
								   P_DATA_FIM   VARCHAR(11))
BEGIN 
    IF P_CODIGO IS NOT NULL THEN
		SELECT * FROM BRP_PESSOAS WHERE PES_CODIGO = P_CODIGO;
	ELSEIF P_DATA_FIM IS NOT NULL AND P_DATA_INI IS NOT NULL THEN
		SELECT * FROM BRP_PESSOAS WHERE PES_DATA_NASCIMENTO BETWEEN DATE_FORMAT(STR_TO_DATE(P_DATA_INI, '%d/%m/%Y'), '%Y-%m-%d')
																AND DATE_FORMAT(STR_TO_DATE(P_DATA_FIM, '%d/%m/%Y'), '%Y-%m-%d');
	ELSE
		SELECT * FROM BRP_PESSOAS;
    END IF;
END