DROP procedure IF EXISTS `bd_registra_pessoas`.`P_OBTEM_PESSOAS`;
CREATE PROCEDURE `P_OBTEM_ENDERECOS`(P_PES_CODIGO INT)
BEGIN
	IF P_PES_CODIGO IS NOT NULL THEN
		SELECT * FROM BRP_ENDERECOS WHERE END_PES_CODIGO = P_PES_CODIGO;
	ELSE
		SELECT * FROM BRP_ENDERECOS;
    END IF;
END